name: CI

on:
  push:
    branches: [master]
    paths:
      - ./github/workflows/**
      - bcpandas/**
  pull_request:
    paths:
      - bcpandas/**
  workflow_dispatch:
    inputs:
      reason:
        description: "Reason for triggering the workflow"
        required: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests - OS ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, ubuntu-20.04]
        python-version: ["3.8", "3.9", "3.10", "3.11"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --only main,test
      - name: Ubuntu - Pull MSSQL server Docker image
        if: startsWith(matrix.os,'ubuntu')
        run: docker pull mcr.microsoft.com/mssql/server:2022-latest
      - name: Ubuntu - Install BCP Utility
        if: startsWith(matrix.os,'ubuntu')
        run: |
          # https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15#ubuntu
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo apt-get install mssql-tools unixodbc-dev
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          source ~/.bashrc
      - name: Windows - Setup MSSQL localdb
        if: startsWith(matrix.os,'windows')
        uses: potatoqualitee/mssqlsuite@v1.7
        with:
          install: localdb
      - name: Test BCP
        run: bcp -v
      - name: Run tests
        run: poetry run python -m pytest -x --cov-report=xml tests
      - name: Upload codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
